apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: endocode-app
  name: endocode-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-endocode-app
